#================================ General =====================================
name: myHostName
tags: ["myTag", "myHostName"]
fields:
  env: myEnv

#============================= Elastic Cloud ==================================
# These settings simplify using winlogbeat with the Elastic Cloud (https://cloud.elastic.co/).
cloud.id: "My_Elastic_Cloud_Deployment:abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ"
cloud.auth: "data_shipper:0987654321abcDEF"
